structures:
  buriedtreasure: true
  desertpyramid: true
  endcity: true
  fortress: true
  igloo: true
  junglepyramid: true
  mansion: true
  mineshaft: true
  monument: true
  oceanruin: true
  shipwreck: true
  stronghold: true
  swamphut: true
  village: true
layer:
  name: "结构"
  hidebydefault: true
  layerprio: 10
  nolabels: false
  minzoom: 0
  inc-coord: true
